#!/usr/bin/env bash
# script displays the contents of the current directory in a list format
# Only the part of the name after the first dash is displayed
for file in *
do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]
    then
        name="${file#*-}"
        echo "$name"
    fi
done
