#!/usr/bin/env bash
# Configures Ubuntu server with new IP addresses
#localhost resolves to 127.0.0.1 and facebook.com resolves to 157.240.11.35
#localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/^127.*localhost$/127.0.0.2\ localhost/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
